source 'https://github.com/CocoaPods/Specs.git'

target 'MSAlertController', :exclusive => true do
  pod "MSAlertController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MSAlertController", :path => "../"

  
end
